using Snap.Data.Mapper.Abstraction;
using Snap.Data.Mapper.Model.ExcelBinOutput;
using Snap.Data.Mapper.Model.ExcelBinOutput.Ability;
using Snap.Data.Mapper.Model.ExcelBinOutput.Achievement;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.ArenaChallenge;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Bartender;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.BlessingScan;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.BlitzRush;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.BonusActivity;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.BounceConjuring;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.BuoyantCombat;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.ChannellerSlab;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Chess;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.CrystalLink;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Delivery;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Dig;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.DragonSpine;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.EchoShell;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Effigy;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.FindHilichurl;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Firework;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.FleurFair;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.FlightActivity;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Hachi;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.HideAndSeek;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Irodori;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Irodori.Chess;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Irodori.Flower;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Irodori.Master;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Irodori.Poetry;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Lamp;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.LanV2;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.LanV2.Firework;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.LanV2.Projection;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.LunaRite;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Mechanicus;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Michiae;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.MistTrial;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.MoonfinTrial;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.MusicGame;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.NewActivity;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.OpActivity;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Oraionokami;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Photograph;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.PlantFlower;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Potion;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.RegionSearch;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Roguelike;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Salesman;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Salvage;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.SeaLampSection;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Shop;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.SignIn;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Spice;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.SteepleChase;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.SummerTime;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Sumo;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.Tanuki;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.TreasureMap;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.TrialAvatar;
using Snap.Data.Mapper.Model.ExcelBinOutput.Activity.WinterCamp;
using Snap.Data.Mapper.Model.ExcelBinOutput.Animal;
using Snap.Data.Mapper.Model.ExcelBinOutput.Aster;
using Snap.Data.Mapper.Model.ExcelBinOutput.AttackAttenuation;
using Snap.Data.Mapper.Model.ExcelBinOutput.Avatar;
using Snap.Data.Mapper.Model.ExcelBinOutput.Bargain;
using Snap.Data.Mapper.Model.ExcelBinOutput.BattlePass;
using Snap.Data.Mapper.Model.ExcelBinOutput.Blossom;
using Snap.Data.Mapper.Model.ExcelBinOutput.Book;
using Snap.Data.Mapper.Model.ExcelBinOutput.Bored;
using Snap.Data.Mapper.Model.ExcelBinOutput.Buff;
using Snap.Data.Mapper.Model.ExcelBinOutput.Capture;
using Snap.Data.Mapper.Model.ExcelBinOutput.City;
using Snap.Data.Mapper.Model.ExcelBinOutput.Cook;
using Snap.Data.Mapper.Model.ExcelBinOutput.Coop;
using Snap.Data.Mapper.Model.ExcelBinOutput.CustomGadget;
using Snap.Data.Mapper.Model.ExcelBinOutput.CustomLevel;
using Snap.Data.Mapper.Model.ExcelBinOutput.Daily;
using Snap.Data.Mapper.Model.ExcelBinOutput.Dialog;
using Snap.Data.Mapper.Model.ExcelBinOutput.Draft;
using Snap.Data.Mapper.Model.ExcelBinOutput.Dungeon;
using Snap.Data.Mapper.Model.ExcelBinOutput.Element;
using Snap.Data.Mapper.Model.ExcelBinOutput.Emoji;
using Snap.Data.Mapper.Model.ExcelBinOutput.EnvAnimal;
using Snap.Data.Mapper.Model.ExcelBinOutput.Exhibition;
using Snap.Data.Mapper.Model.ExcelBinOutput.Expedition;
using Snap.Data.Mapper.Model.ExcelBinOutput.Explore;
using Snap.Data.Mapper.Model.ExcelBinOutput.FeatureTag;
using Snap.Data.Mapper.Model.ExcelBinOutput.Fetter;
using Snap.Data.Mapper.Model.ExcelBinOutput.Fish;
using Snap.Data.Mapper.Model.ExcelBinOutput.Forge;
using Snap.Data.Mapper.Model.ExcelBinOutput.Furniture;
using Snap.Data.Mapper.Model.ExcelBinOutput.Gadget;
using Snap.Data.Mapper.Model.ExcelBinOutput.Gather;
using Snap.Data.Mapper.Model.ExcelBinOutput.Giving;
using Snap.Data.Mapper.Model.ExcelBinOutput.Group;
using Snap.Data.Mapper.Model.ExcelBinOutput.Guide;
using Snap.Data.Mapper.Model.ExcelBinOutput.H5Activity;
using Snap.Data.Mapper.Model.ExcelBinOutput.Homeworld;
using Snap.Data.Mapper.Model.ExcelBinOutput.Hunting;
using Snap.Data.Mapper.Model.ExcelBinOutput.Investigation;
using Snap.Data.Mapper.Model.ExcelBinOutput.LevelTag;
using Snap.Data.Mapper.Model.ExcelBinOutput.Map;
using Snap.Data.Mapper.Model.ExcelBinOutput.Match;
using Snap.Data.Mapper.Model.ExcelBinOutput.Material;
using Snap.Data.Mapper.Model.ExcelBinOutput.MiracleRing;
using Snap.Data.Mapper.Model.ExcelBinOutput.Monster;
using Snap.Data.Mapper.Model.ExcelBinOutput.MpPlay;
using Snap.Data.Mapper.Model.ExcelBinOutput.Music;
using Snap.Data.Mapper.Model.ExcelBinOutput.Npc;
using Snap.Data.Mapper.Model.ExcelBinOutput.Offering;
using Snap.Data.Mapper.Model.ExcelBinOutput.PersonalLine;
using Snap.Data.Mapper.Model.ExcelBinOutput.Photograph;
using Snap.Data.Mapper.Model.ExcelBinOutput.PlayerLevel;
using Snap.Data.Mapper.Model.ExcelBinOutput.Product;
using Snap.Data.Mapper.Model.ExcelBinOutput.PSActivity;
using Snap.Data.Mapper.Model.ExcelBinOutput.PushTip;
using Snap.Data.Mapper.Model.ExcelBinOutput.QTE;
using Snap.Data.Mapper.Model.ExcelBinOutput.Quest;
using Snap.Data.Mapper.Model.ExcelBinOutput.RandomQuest;
using Snap.Data.Mapper.Model.ExcelBinOutput.RandTask;
using Snap.Data.Mapper.Model.ExcelBinOutput.RefreshIndex;
using Snap.Data.Mapper.Model.ExcelBinOutput.Reliquary;
using Snap.Data.Mapper.Model.ExcelBinOutput.Reminder;
using Snap.Data.Mapper.Model.ExcelBinOutput.Reputation;
using Snap.Data.Mapper.Model.ExcelBinOutput.Reunion;
using Snap.Data.Mapper.Model.ExcelBinOutput.Reward;
using Snap.Data.Mapper.Model.ExcelBinOutput.Room;
using Snap.Data.Mapper.Model.ExcelBinOutput.Routine;
using Snap.Data.Mapper.Model.ExcelBinOutput.Scene;
using Snap.Data.Mapper.Model.ExcelBinOutput.Shop;
using Snap.Data.Mapper.Model.ExcelBinOutput.Tower;
using Snap.Data.Mapper.Model.ExcelBinOutput.Tree;
using Snap.Data.Mapper.Model.ExcelBinOutput.Tutorial;
using Snap.Data.Mapper.Model.ExcelBinOutput.Vehicle;
using Snap.Data.Mapper.Model.ExcelBinOutput.Weapon;
using Snap.Data.Mapper.Model.ExcelBinOutput.Weather;
using Snap.Data.Mapper.Model.ExcelBinOutput.Widget;
using Snap.Data.Mapper.Model.ExcelBinOutput.World;
using System.IO;

namespace Snap.Data.Mapper.Model.ObjectModel;
public static partial class ExcelBin
{
    public static IList<NamedValue<Lazy<IOutputHandler>>> Initialize(string genshinDataFolder)
    {
        string targetFolder = Path.Combine(genshinDataFolder, "ExcelBinOutput");

        handlers =  new List<NamedValue<Lazy<IOutputHandler>>>
        {
            Register<AbilityOverrideExcelConfigData>(targetFolder),
            Register<AbilityPropExcelConfigData>(targetFolder),
            Register<AbilityStateResistanceByIDExcelConfigData>(targetFolder),
            Register<AchievementExcelConfigData>(targetFolder),
            Register<AchievementGoalExcelConfigData>(targetFolder),
            Register<ActivityAbilityGroupExcelConfigData>(targetFolder),
            Register<ActivityArenaChallengeExcelConfigData>(targetFolder),
            Register<ActivityArenaChallengeLevelInfoExcelConfigData>(targetFolder),
            Register<ActivityArenaChallengePreviewExcelConfigData>(targetFolder),
            Register<ActivityBannerExcelConfigData>(targetFolder),
            Register<ActivityChessAffixExcelConfigData>(targetFolder),
            Register<ActivityChessCardExcelConfigData>(targetFolder),
            Register<ActivityChessGearExcelConfigData>(targetFolder),
            Register<ActivityChessLevelExcelConfigData>(targetFolder),
            Register<ActivityChessMapExcelConfigData>(targetFolder),
            Register<ActivityChessMapPointExcelConfigData>(targetFolder),
            Register<ActivityChessPreviewExcelConfigData>(targetFolder),
            Register<ActivityChessScheduleExcelConfigData>(targetFolder),
            Register<ActivityCrystalLinkCondBuffExcelConfigData>(targetFolder),
            Register<ActivityCrystalLinkDifficultyExcelConfigData>(targetFolder),
            Register<ActivityCrystalLinkEffectBuffExcelConfigData>(targetFolder),
            Register<ActivityCrystalLinkLevelExcelConfigData>(targetFolder),
            Register<ActivityDeliveryDailyExcelConfigData>(targetFolder),
            Register<ActivityDeliveryExcelConfigData>(targetFolder),
            Register<ActivityDeliveryWatcherDataConfigData>(targetFolder),
            Register<ActivityExcelConfigData>(targetFolder),
            Register<ActivityGroupLinksExcelConfigData>(targetFolder),
            Register<ActivityHachiFinalStageExcelConfigData>(targetFolder),
            Register<ActivityHachiStageExcelConfigData>(targetFolder),
            Register<ActivityHideAndSeekBasicConfigData>(targetFolder),
            Register<ActivityMistTrialAvatarDataExcelConfigData>(targetFolder),
            Register<ActivityMistTrialLevelDataExcelConfigData>(targetFolder),
            Register<ActivityMistTrialLevelFactorExcelConfigData>(targetFolder),
            Register<ActivityMistTrialStatisticsListExcelConfigData>(targetFolder),
            Register<ActivityMistTrialWatcherListDataExcelConfigData>(targetFolder),
            Register<ActivityPhotographExcelConfigData>(targetFolder),
            Register<ActivityPhotographPosExcelConfigData>(targetFolder),
            Register<ActivityPlantFlowerDailyExcelConfigData>(targetFolder),
            Register<ActivityPlantFlowerMainExcelConfigData>(targetFolder),
            Register<ActivityPotionBuffExcelConfigData>(targetFolder),
            Register<ActivityPotionDifficultyExcelConfigData>(targetFolder),
            Register<ActivityPotionLevelExcelConfigData>(targetFolder),
            Register<ActivityPotionModeChoiceExcelConfigData>(targetFolder),
            Register<ActivityPotionOverallExcelConfigData>(targetFolder),
            Register<ActivityPotionStageExcelConfigData>(targetFolder),
            Register<ActivitySalesmanDailyExcelConfigData>(targetFolder),
            Register<ActivitySalesmanExcelConfigData>(targetFolder),
            Register<ActivitySalesmanRewardMatchConfigData>(targetFolder),
            Register<ActivityShopOverallExcelConfigData>(targetFolder),
            Register<ActivityShopSheetExcelConfigData>(targetFolder),
            Register<ActivitySkillExcelConfigData>(targetFolder),
            Register<ActivitySpiceExcelConfigData>(targetFolder),
            Register<ActivitySpiceFoodExcelConfigData>(targetFolder),
            Register<ActivitySpiceGivingExcelConfigData>(targetFolder),
            Register<ActivitySpiceStageDataExcelConfigData>(targetFolder),
            Register<ActivitySteepleChaseConfigData>(targetFolder),
            Register<ActivitySummerTimeExcelConfigData>(targetFolder),
            Register<ActivitySummerTimeFloatSignalExcelConfigData>(targetFolder),
            Register<ActivitySummerTimeRaceExcelConfigData>(targetFolder),
            Register<ActivitySummerTimeRacePreviewExcelConfigData>(targetFolder),
            Register<ActivitySummerTimeStageExcelConfigData>(targetFolder),
            Register<ActivitySumoDifficultyExcelConfigData>(targetFolder),
            Register<ActivitySumoOverallConfigData>(targetFolder),
            Register<ActivitySumoStageExcelConfigData>(targetFolder),
            Register<ActivitySumoSwitchSkillExcelConfigData>(targetFolder),
            Register<ActivityTanukiTravelDataExcelConfigData>(targetFolder),
            Register<ActivityTanukiTravelRouteDataExcelConfigData>(targetFolder),
            Register<ActivityUpAvatarExcelConfigData>(targetFolder),
            Register<ActivityWatcherConfigData>(targetFolder),
            Register<AnimalCodexExcelConfigData>(targetFolder),
            Register<AnimalDescribeExcelConfigData>(targetFolder),
            Register<AsterActivityPerviewExcelConfigData>(targetFolder),
            Register<AsterAvatarUpExcelConfigData>(targetFolder),
            Register<AsterLittleExcelConfigData>(targetFolder),
            Register<AsterMidDifficultyExcelConfigData>(targetFolder),
            Register<AsterMidExcelConfigData>(targetFolder),
            Register<AsterMidGroupsExcelConfigData>(targetFolder),
            Register<AsterMissionExcelConfigData>(targetFolder),
            Register<AsterStageExcelConfigData>(targetFolder),
            Register<AsterTeamBuffExcelConfigData>(targetFolder),
            Register<AttackAttenuationExcelConfigData>(targetFolder),
            Register<AvatarCodexExcelConfigData>(targetFolder),
            Register<AvatarCostumeExcelConfigData>(targetFolder),
            Register<AvatarCurveExcelConfigData>(targetFolder),
            Register<AvatarExcelConfigData>(targetFolder),
            Register<AvatarFettersLevelExcelConfigData>(targetFolder),
            Register<AvatarFlycloakExcelConfigData>(targetFolder),
            Register<AvatarHeroEntityExcelConfigData>(targetFolder),
            Register<AvatarLevelExcelConfigData>(targetFolder),
            Register<AvatarPromoteExcelConfigData>(targetFolder),
            Register<AvatarSkillDepotExcelConfigData>(targetFolder),
            Register<AvatarSkillExcelConfigData>(targetFolder),
            Register<AvatarTalentExcelConfigData>(targetFolder),
            Register<BargainExcelConfigData>(targetFolder),
            Register<BartenderAffixExcelConfigData>(targetFolder),
            Register<BartenderBasicExcelConfigData>(targetFolder),
            Register<BartenderEventExcelConfigData>(targetFolder),
            Register<BartenderFormulaExcelConfigData>(targetFolder),
            Register<BartenderFormulaTypeConfigData>(targetFolder),
            Register<BartenderLevelExcelConfigData>(targetFolder),
            Register<BartenderMaterialUnlockConfigData>(targetFolder),
            Register<BartenderOrderExcelConfigData>(targetFolder),
            Register<BartenderTaskExcelConfigData>(targetFolder),
            Register<BartenderTaskOrderExcelConfigData>(targetFolder),
            Register<BattlePassLevelExcelConfigData>(targetFolder),
            Register<BattlePassMissionExcelConfigData>(targetFolder),
            Register<BattlePassRewardExcelConfigData>(targetFolder),
            Register<BattlePassScheduleExcelConfigData>(targetFolder),
            Register<BattlePassStoryExcelConfigData>(targetFolder),
            Register<BirthdayMailExcelConfigData>(targetFolder),
            Register<BlessingScanExcelConfigData>(targetFolder),
            Register<BlessingScanPicExcelConfigData>(targetFolder),
            Register<BlessingScanTypeExcelConfigData>(targetFolder),
            Register<BlitzRushExcelConfigData>(targetFolder),
            Register<BlitzRushParkourExcelConfigData>(targetFolder),
            Register<BlitzRushStageExcelConfigData>(targetFolder),
            Register<BlossomChestExcelConfigData>(targetFolder),
            Register<BlossomGroupsExcelConfigData>(targetFolder),
            Register<BlossomOpenExcelConfigData>(targetFolder),
            Register<BlossomRefreshExcelConfigData>(targetFolder),
            Register<BlossomReviseExcelConfigData>(targetFolder),
            Register<BlossomSectionOrderExcelConfigData>(targetFolder),
            Register<BlossomTalkExcelConfigData>(targetFolder),
            Register<BonusActivityClientExcelConfigData>(targetFolder),
            Register<BonusActivityExcelConfigData>(targetFolder),
            Register<BonusTreasureSolutionExcelConfigData>(targetFolder),
            Register<BooksCodexExcelConfigData>(targetFolder),
            RegisterIndexable<BookSuitExcelConfigData>(targetFolder),
            Register<BoredActionPriorityExcelConfigData>(targetFolder),
            Register<BoredCreateMonsterExcelConfigData>(targetFolder),
            Register<BoredEventExcelConfigData>(targetFolder),
            Register<BoredMonsterPoolConfigData>(targetFolder),
            Register<BounceConjuringChapterExcelConfigData>(targetFolder),
            Register<BounceConjuringItemExcelConfigData>(targetFolder),
            Register<BounceConjuringPreviewExcelConfigData>(targetFolder),
            Register<BuffExcelConfigData>(targetFolder),
            Register<BuffIconExcelConfigData>(targetFolder),
            Register<BuoyantCombatExcelConfigData>(targetFolder),
            Register<BuoyantCombatLevelExcelConfigData>(targetFolder),
            Register<CampExcelConfigData>(targetFolder),
            Register<CaptureExcelConfigData>(targetFolder),
            Register<CaptureTagsExcelConfigData>(targetFolder),
            Register<ChannellerSlabBuffCostExcelConfigData>(targetFolder),
            Register<ChannellerSlabBuffEnergyExcelConfigData>(targetFolder),
            Register<ChannellerSlabBuffExcelConfigData>(targetFolder),
            Register<ChannellerSlabChapterExcelConfigData>(targetFolder),
            Register<ChannellerSlabDungeonExcelConfigData>(targetFolder),
            Register<ChannellerSlabLevelExcelConfigData>(targetFolder),
            Register<ChannellerSlabLoopDungeonConditionExcelConfigData>(targetFolder),
            Register<ChannellerSlabLoopDungeonDifficultyExcelConfigData>(targetFolder),
            Register<ChannellerSlabLoopDungeonExcelConfigData>(targetFolder),
            Register<ChannellerSlabLoopDungeonPreviewExcelConfigData>(targetFolder),
            Register<ChannellerSlabLoopDungeonRewardExcelConfigData>(targetFolder),
            Register<ChannellerSlabPreviewExcelConfigData>(targetFolder),
            Register<ChapterExcelConfigData>(targetFolder),
            Register<ChargeBarStyleExcelConfigData>(targetFolder),
            Register<ChatExcelConfigData>(targetFolder),
            Register<ChestLevelSetConfigData>(targetFolder),
            Register<CityConfigData>(targetFolder),
            Register<CityLevelupConfigData>(targetFolder),
            Register<CityTaskOpenExcelConfigData>(targetFolder),
            Register<ClientSceneTagConfigData>(targetFolder),
            Register<CombatEndCleanExcelConfigData>(targetFolder),
            Register<CombineExcelConfigData>(targetFolder),
            Register<CompoundExcelConfigData>(targetFolder),
            Register<ConstValueExcelConfigData>(targetFolder),
            Register<CookBonusExcelConfigData>(targetFolder),
            Register<CookRecipeExcelConfigData>(targetFolder),
            Register<CoopActivityExcelConfigData>(targetFolder),
            Register<CoopCGExcelConfigData>(targetFolder),
            Register<CoopChapterExcelConfigData>(targetFolder),
            Register<CoopExcelConfigData>(targetFolder),
            Register<CoopInteractionExcelConfigData>(targetFolder),
            Register<CoopPointExcelConfigData>(targetFolder),
            Register<CoopRewardExcelConfigData>(targetFolder),
            Register<CusmtomGadgetConfigIdExcelConfigData>(targetFolder),
            Register<CusmtomGadgetSlotExcelConfigData>(targetFolder),
            Register<CustomGadgetRootExcelConfigData>(targetFolder),
            Register<CustomGadgetTabExcelConfigData>(targetFolder),
            Register<CustomLevelComponentConfigData>(targetFolder),
            Register<CustomLevelComponentLimitConfigData>(targetFolder),
            Register<CustomLevelComponentTypeConfigData>(targetFolder),
            Register<CustomLevelDungeonConfigData>(targetFolder),
            Register<CustomLevelGroupConfigData>(targetFolder),
            Register<CustomLevelTagConfigData>(targetFolder),
            Register<CustomLevelTagSortConfigData>(targetFolder),
            Register<CustomLevelUIConfigData>(targetFolder),
            Register<CutsceneExcelConfigData>(targetFolder),
            Register<DailyDungeonConfigData>(targetFolder),
            Register<DailyTaskExcelConfigData>(targetFolder),
            Register<DailyTaskLevelExcelConfigData>(targetFolder),
            Register<DailyTaskRewardExcelConfigData>(targetFolder),
            Register<DialogExcelConfigData>(targetFolder),
            Register<DialogSelectTimeOutExcelConfigData>(targetFolder),
            Register<DieTypeTipsExcelConfigData>(targetFolder),
            Register<DigGroupLinkExcelConfigData>(targetFolder),
            Register<DigOverAllExcelConfigData>(targetFolder),
            Register<DigStageDataExcelConfigData>(targetFolder),
            Register<DisplayItemExcelConfigData>(targetFolder),
            Register<DocumentExcelConfigData>(targetFolder),
            Register<DraftExcelConfigData>(targetFolder),
            Register<DraftTextDataExcelConfigData>(targetFolder),
            Register<DragonSpineEnhanceExcelConfigData>(targetFolder),
            Register<DragonSpineMissionExcelConfigData>(targetFolder),
            Register<DragonSpinePreviewExcelConfigData>(targetFolder),
            Register<DragonSpineStageExcelConfigData>(targetFolder),
            Register<DungeonChallengeConfigData>(targetFolder),
            Register<DungeonElementChallengeExcelConfigData>(targetFolder),
            Register<DungeonEntryExcelConfigData>(targetFolder),
            Register<DungeonExcelConfigData>(targetFolder),
            Register<DungeonLevelEntityConfigData>(targetFolder),
            Register<DungeonMapAreaExcelConfigData>(targetFolder),
            Register<DungeonPassExcelConfigData>(targetFolder),
            Register<DungeonRosterConfigData>(targetFolder),
            Register<DungeonSerialConfigData>(targetFolder),
            Register<DynamicInteractionExcelConfigData>(targetFolder),
            Register<EchoShellExcelConfigData>(targetFolder),
            Register<EchoShellFloatSignalExcelConfigData>(targetFolder),
            Register<EchoShellRewardExcelConfigData>(targetFolder),
            Register<EchoShellStoryExcelConfigData>(targetFolder),
            Register<EffigyChallengeExcelConfigData>(targetFolder),
            Register<EffigyDifficultyExcelConfigData>(targetFolder),
            Register<EffigyLimitingConditionExcelConfigData>(targetFolder),
            Register<EffigyRewardExcelConfigData>(targetFolder),
            Register<ElementCoeffExcelConfigData>(targetFolder),
            Register<ElementStateExcelConfigData>(targetFolder),
            Register<EmbeddedTextMapConfigData>(targetFolder),
            Register<EmojiDataExcelConfigData>(targetFolder),
            Register<EmojiSetDataExcelConfigData>(targetFolder),
            Register<EmotionTemplateExcelConfigData>(targetFolder),
            Register<EndureTemplateExcelConfigData>(targetFolder),
            Register<EntityMultiPlayerExcelConfigData>(targetFolder),
            Register<EnvAnimalGatherExcelConfigData>(targetFolder),
            Register<EnvAnimalWeightExcelConfigData>(targetFolder),
            Register<EquipAffixExcelConfigData>(targetFolder),
            Register<ExhibitionCardExcelConfigData>(targetFolder),
            Register<ExhibitionListExcelConfigData>(targetFolder),
            Register<ExhibitionScoreExcelConfigData>(targetFolder),
            Register<ExpeditionActivityMarkerExcelConfigData>(targetFolder),
            Register<ExpeditionActivityPreviewExcelConfigData>(targetFolder),
            Register<ExpeditionBonusExcelConfigData>(targetFolder),
            Register<ExpeditionChallengeExcelConfigData>(targetFolder),
            Register<ExpeditionDataExcelConfigData>(targetFolder),
            Register<ExpeditionDifficultyExcelConfigData>(targetFolder),
            Register<ExpeditionPathExcelConfigData>(targetFolder),
            Register<ExploreAreaTotalExpExcelConfigData>(targetFolder),
            Register<ExploreExcelConfigData>(targetFolder),
            Register<FeatureTagExcelConfigData>(targetFolder),
            Register<FeatureTagGroupExcelConfigData>(targetFolder),
            Register<FetterCharacterCardExcelConfigData>(targetFolder),
            Register<FetterInfoExcelConfigData>(targetFolder),
            Register<FettersExcelConfigData>(targetFolder),
            Register<FetterStoryExcelConfigData>(targetFolder),
            Register<FindHilichurlAssignmentExcelConfigData>(targetFolder),
            Register<FindHilichurlExcelConfigData>(targetFolder),
            Register<FindHilichurlHiliWeiExcelConfigData>(targetFolder),
            Register<FireworksExcelConfigData>(targetFolder),
            Register<FireworksFactorExcelConfigData>(targetFolder),
            Register<FireworksLaunchExcelConfigData>(targetFolder),
            Register<FishBaitExcelConfigData>(targetFolder),
            Register<FishExcelConfigData>(targetFolder),
            Register<FishPoolExcelConfigData>(targetFolder),
            Register<FishRodExcelConfigData>(targetFolder),
            Register<FishSkillExcelConfigData>(targetFolder),
            Register<FishStockExcelConfigData>(targetFolder),
            Register<FleurFairBuffEnergyStatExcelConfigData>(targetFolder),
            Register<FleurFairChapterExcelConfigData>(targetFolder),
            Register<FleurFairDungeonExcelConfigData>(targetFolder),
            Register<FleurFairDungeonStatExcelConfigData>(targetFolder),
            Register<FleurFairMiniGameExcelConfigData>(targetFolder),
            Register<FleurFairPreviewExcelConfigData>(targetFolder),
            Register<FleurFairTipsExcelConfigData>(targetFolder),
            Register<FlightActivityDayExcelConfigData>(targetFolder),
            Register<FlightActivityExcelConfigData>(targetFolder),
            Register<FlightActivityMedalExcelConfigData>(targetFolder),
            Register<ForgeExcelConfigData>(targetFolder),
            Register<ForgeRandomExcelConfigData>(targetFolder),
            Register<ForgeUpdateExcelConfigData>(targetFolder),
            Register<FurnitureMakeExcelConfigData>(targetFolder),
            Register<FurnitureSuiteExcelConfigData>(targetFolder),
            Register<GadgetChainExcelConfigData>(targetFolder),
            Register<GadgetCurveExcelConfigData>(targetFolder),
            RegisterIndexable<GadgetExcelConfigData>(targetFolder),
            Register<GadgetGuestExcelConfigData>(targetFolder),
            Register<GadgetInteractExcelConfigData>(targetFolder),
            Register<GadgetPropExcelConfigData>(targetFolder),
            Register<GadgetTitleExcelConfigData>(targetFolder),
            Register<GalleryExcelConfigData>(targetFolder),
            Register<GatherBundleExcelConfigData>(targetFolder),
            Register<GatherExcelConfigData>(targetFolder),
            Register<GeneralRewardExcelConfigData>(targetFolder),
            Register<GivingExcelConfigData>(targetFolder),
            Register<GivingGroupExcelConfigData>(targetFolder),
            Register<GlobalWatcherConfigData>(targetFolder),
            Register<GroupLinksBundleExcelConfigData>(targetFolder),
            Register<GroupLinksBundleRewardExcelConfigData>(targetFolder),
            Register<GroupTagExcelConfigData>(targetFolder),
            Register<GuideRatingExcelConfigData>(targetFolder),
            Register<GuideTriggerExcelConfigData>(targetFolder),
            Register<H5ActivityExcelConfigData>(targetFolder),
            Register<H5ActivityWatcherExcelConfigData>(targetFolder),
            Register<HideAndSeekAvatarSDExcelConfigData>(targetFolder),
            Register<HideAndSeekMatchExcelConfigData>(targetFolder),
            Register<HideAndSeekSkillExcelConfigData>(targetFolder),
            Register<HitLevelTemplateExcelConfigData>(targetFolder),
            Register<HomeworldAnimalExcelConfigData>(targetFolder),
            Register<HomeWorldAreaComfortExcelConfigData>(targetFolder),
            Register<HomeWorldBgmExcelConfigData>(targetFolder),
            Register<HomeWorldCameraExcelConfigData>(targetFolder),
            Register<HomeWorldComfortLevelExcelConfigData>(targetFolder),
            Register<HomeWorldCustomFurnitureSlotExcelConfigData>(targetFolder),
            Register<HomeWorldEventExcelConfigData>(targetFolder),
            Register<HomeWorldExtraFurnitureExcelConfigData>(targetFolder),
            Register<HomeWorldFarmFieldExcelConfigData>(targetFolder),
            Register<HomeworldFurnitureDeployRulesetData>(targetFolder),
            Register<HomeWorldFurnitureExcelConfigData>(targetFolder),
            Register<HomeWorldFurnitureTypeExcelConfigData>(targetFolder),
            Register<HomeWorldInteractiveNPCExcelConfigData>(targetFolder),
            Register<HomeWorldLeastShopExcelConfigData>(targetFolder),
            Register<HomeworldLevelExcelConfigData>(targetFolder),
            Register<HomeWorldLimitShopExcelConfigData>(targetFolder),
            Register<HomeworldModuleExcelConfigData>(targetFolder),
            Register<HomeWorldNPCExcelConfigData>(targetFolder),
            Register<HomeworldNPCExcelDataData>(targetFolder),
            Register<HomeWorldPlantExcelConfigData>(targetFolder),
            Register<HomeWorldServerGadgetExcelConfigData>(targetFolder),
            Register<HomeWorldShopSubTagExcelConfigData>(targetFolder),
            Register<HomeWorldSpecialFurnitureExcelConfigData>(targetFolder),
            Register<HuntingClueGatherExcelConfigData>(targetFolder),
            Register<HuntingClueMonsterExcelConfigData>(targetFolder),
            Register<HuntingClueTextExcelConfigData>(targetFolder),
            Register<HuntingGroupInfoExcelConfigData>(targetFolder),
            Register<HuntingMonsterExcelConfigData>(targetFolder),
            Register<HuntingRefreshExcelConfigData>(targetFolder),
            Register<HuntingRegionExcelConfigData>(targetFolder),
            Register<IconAdsorbEffectExcelConfigData>(targetFolder),
            Register<InvestigationConfigData>(targetFolder),
            Register<InvestigationDungeonConfigData>(targetFolder),
            Register<InvestigationMonsterConfigData>(targetFolder),
            Register<InvestigationTargetConfigData>(targetFolder),
            Register<IrodoriChessAffixExcelConfigData>(targetFolder),
            Register<IrodoriChessCardExcelConfigData>(targetFolder),
            Register<IrodoriChessDisorderExcelConfigData>(targetFolder),
            Register<IrodoriChessGearExcelConfigData>(targetFolder),
            Register<IrodoriChessLevelExcelConfigData>(targetFolder),
            Register<IrodoriChessMapExcelConfigData>(targetFolder),
            Register<IrodoriChessMapPointExcelConfigData>(targetFolder),
            Register<IrodoriExcelConfigData>(targetFolder),
            Register<IrodoriFlowerGroupExcelConfigData>(targetFolder),
            Register<IrodoriFlowerThemeExcelConfigData>(targetFolder),
            Register<IrodoriMasterExcelConfigData>(targetFolder),
            Register<IrodoriMasterLevelExcelConfigData>(targetFolder),
            Register<IrodoriPoetryExcelConfigData>(targetFolder),
            Register<IrodoriPoetryLineExcelConfigData>(targetFolder),
            Register<IrodoriQuestExcelConfigData>(targetFolder),
            Register<LampContributionExcelConfigData>(targetFolder),
            Register<LampPhaseExcelConfigData>(targetFolder),
            Register<LampProgressControlConfigData>(targetFolder),
            Register<LampRegionDataConfigData>(targetFolder),
            Register<LandSoundExcelConfigData>(targetFolder),
            Register<LanV2FireworksChallengeDataExcelConfigData>(targetFolder),
            Register<LanV2FireworksFactorDataExcelConfigData>(targetFolder),
            Register<LanV2FireworksOverallDataExcelConfigData>(targetFolder),
            Register<LanV2FireworksSkillDataExcelConfigData>(targetFolder),
            Register<LanV2FireworksStageDataExcelConfigData>(targetFolder),
            Register<LanV2OverAllDataExcelConfigData>(targetFolder),
            Register<LanV2ProjectionExcelConfigData>(targetFolder),
            Register<LanV2ProjectionLevelExcelConfigData>(targetFolder),
            Register<LanV2ProjectionStageExcelConfigData>(targetFolder),
            Register<LanV2ProjectionSwitchButtonConfigData>(targetFolder),
            Register<LevelSuppressExcelConfigData>(targetFolder),
            Register<LevelTagExcelConfigData>(targetFolder),
            Register<LevelTagGroupsExcelConfigData>(targetFolder),
            Register<LimitRegionExcelConfigData>(targetFolder),
            Register<LoadingSituationExcelConfigData>(targetFolder),
            Register<LoadingTipsExcelConfigData>(targetFolder),
            Register<LocalizationExcelConfigData>(targetFolder),
            Register<LockTemplateExcelConfigData>(targetFolder),
            Register<LunaRiteBattleBuffExcelConfigData>(targetFolder),
            Register<LunaRiteBattleExcelConfigData>(targetFolder),
            Register<LunaRitePreviewExcelConfigData>(targetFolder),
            Register<LunaRiteQuestExcelConfigData>(targetFolder),
            Register<LunaRiteSearchingExcelConfigData>(targetFolder),
            Register<MailExcelConfigData>(targetFolder),
            Register<MainCoopExcelConfigData>(targetFolder),
            Register<MainQuestExcelConfigData>(targetFolder),
            Register<ManualTextMapConfigData>(targetFolder),
            Register<MapAreaConfigData>(targetFolder),
            Register<MapTagDataConfigData>(targetFolder),
            Register<MatchExcelConfigData>(targetFolder),
            Register<MatchingTextDataExcelConfigData>(targetFolder),
            Register<MatchPunishExcelConfigData>(targetFolder),
            Register<MaterialCodexExcelConfigData>(targetFolder),
            RegisterIndexable<MaterialExcelConfigData>(targetFolder),
            Register<MaterialSourceDataExcelConfigData>(targetFolder),
            Register<MechanicBuildingExcelConfigData>(targetFolder),
            Register<MechanicusCardCurseExcelConfigData>(targetFolder),
            Register<MechanicusCardEffectExcelConfigData>(targetFolder),
            Register<MechanicusCardExcelConfigData>(targetFolder),
            Register<MechanicusDifficultyExcelConfigData>(targetFolder),
            Register<MechanicusExcelConfigData>(targetFolder),
            Register<MechanicusGearLevelUpExcelConfigData>(targetFolder),
            Register<MechanicusMapExcelConfigData>(targetFolder),
            Register<MechanicusMapPointExcelConfigData>(targetFolder),
            Register<MechanicusSequenceExcelConfigData>(targetFolder),
            Register<MechanicusWatcherExcelConfigData>(targetFolder),
            Register<MichiaeAntiErosionExcelConfigData>(targetFolder),
            Register<MichiaeBattleSkillExcelConfigData>(targetFolder),
            Register<MichiaeBossChallengeExcelConfigData>(targetFolder),
            Register<MichiaeDarkChallengeExcelConfigData>(targetFolder),
            Register<MichiaeErosionAreaExcelConfigData>(targetFolder),
            Register<MichiaeErosionMapExcelConfigData>(targetFolder),
            Register<MichiaeOfferingDataExcelConfigData>(targetFolder),
            Register<MichiaeOverallExcelConfigData>(targetFolder),
            Register<MichiaePreviewExcelConfigData>(targetFolder),
            Register<MichiaeRadarExcelConfigData>(targetFolder),
            Register<MichiaeStageExcelConfigData>(targetFolder),
            Register<MichiaeWatcherExcelConfigData>(targetFolder),
            Register<MiracleRingDropExcelConfigData>(targetFolder),
            Register<MiracleRingExcelConfigData>(targetFolder),
            Register<MonsterAffixExcelConfigData>(targetFolder),
            Register<MonsterCurveExcelConfigData>(targetFolder),
            Register<MonsterDescribeExcelConfigData>(targetFolder),
            Register<MonsterExcelConfigData>(targetFolder),
            Register<MonsterMultiPlayerExcelConfigData>(targetFolder),
            Register<MonsterRelationshipExcelConfigData>(targetFolder),
            Register<MonsterSpecialNameExcelConfigData>(targetFolder),
            Register<MonsterTitleExcelConfigData>(targetFolder),
            Register<MoonfinTrialExcelConfigData>(targetFolder),
            Register<MoonfinTrialLevelExcelConfigData>(targetFolder),
            Register<MpPlayAbilityGroupExcelConfigData>(targetFolder),
            Register<MpPlayBuffExcelConfigData>(targetFolder),
            Register<MpPlayGroupExcelConfigData>(targetFolder),
            Register<MpPlayLevelTextDataExcelConfigData>(targetFolder),
            Register<MpPlayMatchExcelConfigData>(targetFolder),
            Register<MpPlayScoreExcelConfigData>(targetFolder),
            Register<MpPlayStatisticConfigData>(targetFolder),
            Register<MpPlayTextDataExcelConfigData>(targetFolder),
            Register<MpPlayWatcherConfigData>(targetFolder),
            Register<MultistageExcelConfigData>(targetFolder),
            Register<MusicGameBasicConfigData>(targetFolder),
            Register<MusicGamePositionConfigData>(targetFolder),
            Register<MusicGamePreviewConfigData>(targetFolder),
            Register<MusicInfoConfigData>(targetFolder),
            Register<MusicInstrumentConfigData>(targetFolder),
            Register<NewActivityAvatarSelectionExcelConfigData>(targetFolder),
            Register<NewActivityCondExcelConfigData>(targetFolder),
            Register<NewActivityEntryConfigData>(targetFolder),
            Register<NewActivityExcelConfigData>(targetFolder),
            Register<NewActivityOverlapExcelConfigData>(targetFolder),
            Register<NewActivityPreviewConfigData>(targetFolder),
            Register<NewActivitySaleExcelConfigData>(targetFolder),
            Register<NewActivityScoreLimitExcelConfigData>(targetFolder),
            Register<NewActivityScoreRewardExcelConfigData>(targetFolder),
            Register<NewActivityScoreShowExcelConfigData>(targetFolder),
            Register<NewActivityTimeGroupExcelConfigData>(targetFolder),
            Register<NewActivityWatcherConfigData>(targetFolder),
            Register<NpcCrowdExcelConfigData>(targetFolder),
            Register<NpcExcelConfigData>(targetFolder),
            Register<NpcFirstMetExcelConfigData>(targetFolder),
            Register<OfferingLevelUpExcelConfigData>(targetFolder),
            Register<OfferingLumenStoneExcelConfigData>(targetFolder),
            Register<OfferingOpenStateConfigData>(targetFolder),
            Register<OfferingVersionExcelConfigData>(targetFolder),
            Register<OpActivityBonusExcelConfigData>(targetFolder),
            Register<OpActivityExcelConfigData>(targetFolder),
            Register<OpenStateConfigData>(targetFolder),
            Register<OptionExcelConfigData>(targetFolder),
            Register<OraionokamiDataExcelConfigData>(targetFolder),
            Register<OraionokamiDescExcelConfigData>(targetFolder),
            Register<OverflowTransformExcelConfigData>(targetFolder),
            Register<PerceptionTemplateExcelConfigData>(targetFolder),
            Register<PersonalLineActivityExcelConfigData>(targetFolder),
            Register<PersonalLineExcelConfigData>(targetFolder),
            Register<PhotographCheckAnimatorDataData>(targetFolder),
            Register<PhotographExpressionExcelConfigData>(targetFolder),
            Register<PhotographPoseExcelConfigData>(targetFolder),
            Register<PhotographPosenameExcelConfigData>(targetFolder),
            Register<PhotographTaskData>(targetFolder),
            Register<PlaceNameConfigData>(targetFolder),
            Register<PlayerLevelExcelConfigData>(targetFolder),
            Register<PlayerLevelLockExcelConfigData>(targetFolder),
            Register<PriceTierConfigData>(targetFolder),
            Register<ProductAppleGiftCardDetailConfigData>(targetFolder),
            Register<ProductCardDetailConfigData>(targetFolder),
            Register<ProductConcertPackageDetailConfigData>(targetFolder),
            Register<ProductGoogleGiftCardDetailConfigData>(targetFolder),
            Register<ProductIdConfigData>(targetFolder),
            Register<ProductMcoinDetailConfigData>(targetFolder),
            Register<ProductPlayDetailConfigData>(targetFolder),
            Register<ProductPS4PackageDetailConfigData>(targetFolder),
            Register<ProductPsnCompensationDetailConfigData>(targetFolder),
            Register<ProudSkillExcelConfigData>(targetFolder),
            Register<PS4GroupExcelConfigData>(targetFolder),
            Register<PS5GroupExcelConfigData>(targetFolder),
            Register<PSActivitiesActivityConfigData>(targetFolder),
            Register<PSActivitiesSubTaskConfigData>(targetFolder),
            Register<PSActivitiesTaskConfigData>(targetFolder),
            Register<PushTipsCodexExcelConfigData>(targetFolder),
            Register<PushTipsConfigData>(targetFolder),
            Register<QTEExcelConfigData>(targetFolder),
            Register<QTEStepExcelConfigData>(targetFolder),
            Register<QuestAcceptionMarkExcelConfigData>(targetFolder),
            Register<QuestCodexExcelConfigData>(targetFolder),
            Register<QuestDialogDecoratorExcelConfigData>(targetFolder),
            Register<QuestExcelConfigData>(targetFolder),
            Register<QuestGlobalVarConfigData>(targetFolder),
            Register<QuestPlaceConfigData>(targetFolder),
            Register<QuestResCollectionExcelConfigData>(targetFolder),
            Register<QuestSpecialShowConfigData>(targetFolder),
            Register<QuestSummarizationTextExcelConfigData>(targetFolder),
            Register<RadarHintExcelConfigData>(targetFolder),
            Register<RandomMainQuestExcelConfigData>(targetFolder),
            Register<RandomQuestElemPoolExcelConfigData>(targetFolder),
            Register<RandomQuestEntranceExcelConfigData>(targetFolder),
            Register<RandomQuestExcelConfigData>(targetFolder),
            Register<RandomQuestTemplateExcelConfigData>(targetFolder),
            Register<RandTaskExcelConfigData>(targetFolder),
            Register<RandTaskLevelConfigData>(targetFolder),
            Register<RandTaskRewardConfigData>(targetFolder),
            Register<ReactionEnergyExcelConfigData>(targetFolder),
            Register<RefreshIndexExcelConfigData>(targetFolder),
            Register<RefreshPolicyExcelConfigData>(targetFolder),
            Register<RegionSearchCondExcelConfigData>(targetFolder),
            Register<RegionSearchExcelConfigData>(targetFolder),
            Register<RegionSearchRegionExcelConfigData>(targetFolder),
            Register<ReliquaryAffixExcelConfigData>(targetFolder),
            Register<ReliquaryCodexExcelConfigData>(targetFolder),
            Register<ReliquaryDecomposeExcelConfigData>(targetFolder),
            Register<ReliquaryExcelConfigData>(targetFolder),
            Register<ReliquaryLevelExcelConfigData>(targetFolder),
            Register<ReliquaryMainPropExcelConfigData>(targetFolder),
            Register<ReliquaryPowerupExcelConfigData>(targetFolder),
            Register<ReliquarySetExcelConfigData>(targetFolder),
            Register<ReminderExcelConfigData>(targetFolder),
            Register<ReminderIndexExcelConfigData>(targetFolder),
            Register<ReputationCityExcelConfigData>(targetFolder),
            Register<ReputationEntranceExcelConfigData>(targetFolder),
            Register<ReputationExploreExcelConfigData>(targetFolder),
            Register<ReputationFunctionExcelConfigData>(targetFolder),
            Register<ReputationLevelExcelConfigData>(targetFolder),
            Register<ReputationQuestExcelConfigData>(targetFolder),
            Register<ReputationRequestExcelConfigData>(targetFolder),
            Register<ReunionCommercialExcelConfigData>(targetFolder),
            Register<ReunionMissionExcelConfigData>(targetFolder),
            Register<ReunionPrivilegeExcelConfigData>(targetFolder),
            Register<ReunionScheduleExcelConfigData>(targetFolder),
            Register<ReunionSignInExcelConfigData>(targetFolder),
            Register<ReunionWatcherExcelConfigData>(targetFolder),
            Register<ReviseLevelGrowExcelConfigData>(targetFolder),
            RegisterIndexable<RewardExcelConfigData>(targetFolder),
            Register<RewardPreviewExcelConfigData>(targetFolder),
            Register<RogueCellWeightExcelConfigData>(targetFolder),
            Register<RogueDungeonCellExcelConfigData>(targetFolder),
            Register<RogueGadgetExcelConfigData>(targetFolder),
            Register<RogueGadgetRotConfigData>(targetFolder),
            Register<RoguelikeCardExcelConfigData>(targetFolder),
            Register<RoguelikeCurseExcelConfigData>(targetFolder),
            Register<RoguelikeCursePoolExcelConfigData>(targetFolder),
            Register<RoguelikeRuneExcelConfigData>(targetFolder),
            Register<RoguelikeShikigamiExcelConfigData>(targetFolder),
            Register<RoguelikeShikigamiGroupExcelConfigData>(targetFolder),
            Register<RogueMonsterPoolExcelConfigData>(targetFolder),
            Register<RogueSequenceExcelConfigData>(targetFolder),
            Register<RogueStageExcelConfigData>(targetFolder),
            Register<RogueTokenExcelConfigData>(targetFolder),
            Register<RoomExcelConfigData>(targetFolder),
            Register<RoomWeatherExcelConfigData>(targetFolder),
            Register<RoutineDetailExcelConfigData>(targetFolder),
            Register<RoutineTypeExcelConfigData>(targetFolder),
            Register<RqTalkExcelConfigData>(targetFolder),
            Register<SalvageChallengeDataExcelConfigData>(targetFolder),
            Register<SalvageOverAllExcelConfigData>(targetFolder),
            Register<SalvageStageDataExcelConfigData>(targetFolder),
            Register<SalvageTypeDataExcelConfigData>(targetFolder),
            Register<SceneExcelConfigData>(targetFolder),
            Register<SceneTagConfigData>(targetFolder),
            Register<SeaLampSectionExcelConfigData>(targetFolder),
            Register<SeaLampSectionMainQuestExcelConfigData>(targetFolder),
            Register<SeaLampSectionMiniQuestExcelConfigData>(targetFolder),
            Register<SensitiveWordConfigData>(targetFolder),
            Register<ServerMessageExcelConfigData>(targetFolder),
            Register<ShareCDExcelConfigData>(targetFolder),
            Register<ShopExcelConfigData>(targetFolder),
            Register<ShopGoodsExcelConfigData>(targetFolder),
            Register<ShopmallEntranceExcelConfigData>(targetFolder),
            Register<ShopmallGoodsSaleConfigData>(targetFolder),
            Register<ShopmallRecommendConfigData>(targetFolder),
            Register<ShopmallSubTabExcelConfigData>(targetFolder),
            Register<ShopMaterialOrderExcelConfigData>(targetFolder),
            Register<ShopRotateExcelConfigData>(targetFolder),
            Register<ShopSpecialKeysDataExcelConfigData>(targetFolder),
            Register<SignInCondExcelConfigData>(targetFolder),
            Register<SignInDayExcelConfigData>(targetFolder),
            Register<SignInPeriodExcelConfigData>(targetFolder),
            Register<StateExcelConfigData>(targetFolder),
            Register<StrengthenBasePointExcelConfigData>(targetFolder),
            Register<SystemOpenUIConfigData>(targetFolder),
            Register<TalkExcelConfigData>(targetFolder),
            Register<TalkSelectTimeOutExcelConfigData>(targetFolder),
            Register<TauntLevelTemplateExcelConfigData>(targetFolder),
            Register<TeamResonanceExcelConfigData>(targetFolder),
            Register<TemplateReminderExcelConfigData>(targetFolder),
            Register<TowerBuffExcelConfigData>(targetFolder),
            Register<TowerFloorExcelConfigData>(targetFolder),
            Register<TowerLevelExcelConfigData>(targetFolder),
            Register<TowerRewardExcelConfigData>(targetFolder),
            Register<TowerScheduleExcelConfigData>(targetFolder),
            Register<TowerSkipFloorExcelConfigData>(targetFolder),
            Register<TransPointRewardConfigData>(targetFolder),
            Register<TreasureMapBonusRegionExcelConfigData>(targetFolder),
            Register<TreasureMapExcelConfigData>(targetFolder),
            Register<TreasureMapRegionExcelConfigData>(targetFolder),
            Register<TreeDropExcelConfigData>(targetFolder),
            Register<TreeTypeExcelConfigData>(targetFolder),
            Register<TrialAvatarActivityDataExcelConfigData>(targetFolder),
            Register<TrialAvatarActivityExcelConfigData>(targetFolder),
            Register<TrialAvatarExcelConfigData>(targetFolder),
            Register<TrialAvatarFetterDataConfigData>(targetFolder),
            Register<TrialAvatarTemplateExcelConfigData>(targetFolder),
            Register<TrialReliquaryExcelConfigData>(targetFolder),
            Register<TriggerExcelConfigData>(targetFolder),
            Register<TutorialDetailExcelConfigData>(targetFolder),
            Register<TutorialExcelConfigData>(targetFolder),
            Register<UidOpNotifyExcelConfigData>(targetFolder),
            Register<UIInteractExcelConfigData>(targetFolder),
            Register<VehicleMarkExcelConfigData>(targetFolder),
            Register<VehicleSkillDepotExcelConfigData>(targetFolder),
            Register<VehicleSkillExcelConfigData>(targetFolder),
            Register<ViewCodexExcelConfigData>(targetFolder),
            Register<WeaponCodexExcelConfigData>(targetFolder),
            Register<WeaponCurveExcelConfigData>(targetFolder),
            Register<WeaponExcelConfigData>(targetFolder),
            Register<WeaponLevelExcelConfigData>(targetFolder),
            Register<WeaponPromoteExcelConfigData>(targetFolder),
            Register<WeatherExcelConfigData>(targetFolder),
            Register<WeatherTemplateExcelConfigData>(targetFolder),
            Register<WidgetActiveExcelConfigData>(targetFolder),
            Register<WidgetCameraExcelConfigData>(targetFolder),
            Register<WidgetCameraScanExcelConfigData>(targetFolder),
            Register<WidgetExcelConfigData>(targetFolder),
            Register<WidgetGeneralExcelConfigData>(targetFolder),
            Register<WinterCampBattleExcelConfigData>(targetFolder),
            Register<WinterCampExcelConfigData>(targetFolder),
            Register<WinterCampExploreExcelConfigData>(targetFolder),
            Register<WinterCampRaceExcelConfigData>(targetFolder),
            Register<WinterCampRaceItemTipsExcelConfigData>(targetFolder),
            Register<WinterCampSnowmanDetailExcelConfigData>(targetFolder),
            Register<WinterCampSnowmanExcelConfigData>(targetFolder),
            Register<WorldAreaConfigData>(targetFolder),
            Register<WorldAreaExploreEventConfigData>(targetFolder),
            Register<WorldAreaLevelupConfigData>(targetFolder),
            Register<WorldExcelConfigData>(targetFolder),
            Register<WorldLevelExcelConfigData>(targetFolder),
        };

        return handlers;
    }
}

