global using Snap.Data.Mapper.Converter;
global using Snap.Data.Mapper.Converter.ObjectModel;
global using Snap.Data.Mapper.Model.ObjectModel;
global using Snap.Data.Mapper.Model.ObjectModel.Annotation;
global using Snap.Data.Mapper.Model.ObjectModel.Converter;
global using System;
global using System.Collections.Generic;
global using System.Text.Json.Serialization;
global using Microsoft;